<x-admin-layout>
    <x-slot name="header">
        <div>
            <h1 class="jewel-page-title text-xl">Reports</h1>
            <p class="jewel-page-subtitle">Analytics across orders, sales, production, catalog, and billing</p>
        </div>
    </x-slot>

    <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
        @foreach($reportTypes as $reportType)
            <a href="{{ route('admin.reports.show', $reportType) }}"
                class="jewel-card p-5 hover:shadow-jewel-lg hover:-translate-y-0.5 transition group block">
                <div class="flex items-start gap-4">
                    <div class="p-2.5 rounded-xl bg-jewel-gold-light text-jewel-gold-dark group-hover:bg-jewel-gold/20 transition">
                        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="{{ $reportType->icon() }}"/>
                        </svg>
                    </div>
                    <div class="min-w-0">
                        <h2 class="font-semibold text-jewel-dark group-hover:text-jewel-gold-dark transition">{{ $reportType->label() }}</h2>
                        <p class="text-sm text-gray-500 mt-1 line-clamp-2">{{ $reportType->description() }}</p>
                    </div>
                </div>
            </a>
        @endforeach
    </div>

    @if($recentExports->isNotEmpty())
        <div class="jewel-card overflow-hidden">
            <div class="px-6 py-4 border-b border-slate-100">
                <h2 class="font-semibold text-jewel-dark">Recent CSV Exports</h2>
            </div>
            <div class="overflow-x-auto">
                <table class="jewel-table min-w-full">
                    <thead>
                        <tr>
                            <th>Report</th>
                            <th>Period</th>
                            <th>Generated By</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($recentExports as $export)
                            <tr>
                                <td class="px-6 py-3 text-sm font-medium">{{ $export->report_type->label() }}</td>
                                <td class="px-6 py-3 text-sm text-gray-500">
                                    @if($export->date_from && $export->date_to)
                                        {{ $export->date_from->format('M d, Y') }} – {{ $export->date_to->format('M d, Y') }}
                                    @else
                                        All time
                                    @endif
                                </td>
                                <td class="px-6 py-3 text-sm">{{ $export->generator->name }}</td>
                                <td class="px-6 py-3 text-sm text-gray-500">{{ $export->created_at->format('M d, Y H:i') }}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif
</x-admin-layout>
